services:
    test:
        image: klakegg/hugo:ext-ubuntu-onbuild
        command: server -D
        ports: 
          - 1313:1313
        volumes: 
          - .:/src
    compile:
        image: klakegg/hugo:ext-ubuntu-onbuild
        volumes:
        - .:/src
